version: "3"

services:
        django:
                build: .
                command: python3 manage.py runserver 0:8213 --insecure
                ports:
                        - 8213:8213
                volumes:
                        - ./:/django
                networks:
                        - backend
        parser:
                container_name: parser
                build: .
                command: python3 parser.py
                depends_on:
                        - django
                networks:
                        - backend
                extra_hosts:
                        - "host.docker.internal:host-gateway"

networks:
        backend:        
