# Generated by Django 4.0.5 on 2022-07-11 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_privateboard2_privateboard1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commonboard',
            name='content',
            field=models.CharField(max_length=256, verbose_name='내용'),
        ),
    ]
